package launchdarkly

const (
	// keys used in terraform files referencing keys in launchdarkly resource objects.
	// The name of each constant is the same as its value.
	project_key          = "project_key"
	env_key              = "env_key"
	key                  = "key"
	name                 = "name"
	tags                 = "tags"
	environments         = "environments"
	api_key              = "api_key"
	mobile_key           = "mobile_key"
	color                = "color"
	default_ttl          = "default_ttl"
	secure_mode          = "secure_mode"
	default_track_events = "default_track_events"
	description          = "description"
	maintainer_id        = "maintainer_id"
	variation_type       = "variation_type"
	variations           = "variations"
	temporary            = "temporary"
	include_in_snippet   = "include_in_snippet"
	value                = "value"
	url                  = "url"
	secret               = "secret"
	on                   = "on"
	_id                  = "_id"
	resources            = "resources"
	actions              = "actions"
	effect               = "effect"
	policy               = "policy"
	excluded             = "excluded"
	included             = "included"
	custom_properties    = "custom_properties"
	email                = "email"
	first_name           = "first_name"
	last_name            = "last_name"
	role                 = "role"
	custom_roles         = "custom_roles"
	rules                = "rules"
	attribute            = "attribute"
	op                   = "op"
	values               = "values"
	negate               = "negate"
	clauses              = "clauses"
	weight               = "weight"
	bucket_by            = "bucket_by"
)
