package launchdarkly

import (
	"os"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// Code generated by scripts/openapi-provider-gen. DO NOT EDIT.
func generatedFrameworkResources() []func() resource.Resource {
	resources := []func() resource.Resource{
		NewGeneratedProjectResource,
		NewGeneratedTeamResource,
		NewGeneratedTeamRoleMappingResource,
		NewTeamRoleMappingResource,
	}

	return resources
}

func generatedOpenAPIExperimentalEnabled() bool {
	raw := strings.ToLower(strings.TrimSpace(os.Getenv("LD_TERRAFORM_EXPERIMENTAL_GENERATED_RESOURCES")))
	switch raw {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}
