version: 2
repo:
  public: terraform-provider-launchdarkly
  private: terraform-provider-launchdarkly-private

jobs:
  - docker:
      image: golang:1.18-buster
    template:
      name: go
    env: 
      # This won't do anything for now
      SKIP_GITHUB_RELEASE: true

branches:
  - name: main
  