version: 2

repo:
  public: terraform-provider-launchdarkly
  private: terraform-provider-launchdarkly-private
  
jobs:
  - docker:
      image: golang:1.18-buster
      copyGitHistory: true
    template:
      name: go
      # We run the tests as part of every merge
      skip:
        - test

branches:
  - name: main
