name: Jira Issue Linker

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  jira-issue-link:
    runs-on: ubuntu-latest
    if: github.repository == 'launchdarkly/terraform-provider-launchdarkly-private'
    steps:
      - uses: launchdarkly-labs/ld-gh-actions-jira@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
